### ISSUE TITLE
Flaky test reporter also scans presubmit tests

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1375]
Currently flaky test reporter only scans periodic jobs, which run every 2 hours, so only 10 latest runs got scanned. This causes the result often not up-to-date and tend to miss some of the flaky tests (Can be found out by how many times manual /retest made the tests pass). The result doesn't necessarily need to be included in Github/Slack reports, but for sure will make flaky-test-retryer much more robust and reliable

**Comment by Fredy-Z** [comment]
One of my concern for this proposal is, since many (if not most) presubmit tests fail due to non-flaky tests, how do we make sure the data we collect will not pollute our golden data? We can probably only collect failed tests on the PRs' last commit before they are merged, but I'm not sure how doable it will be.

**Comment by chaodaiG** [comment]
@Fredy-Z , polluting our golden data for sure is a top concern in my mind as well. The solution in my mind is we should gather information in PR in a very strict way:
- Only compares runs that have identical source(myFork/serving myBranch) and base(knative/serving master branch) commits with each other
- Exclude runs that failed all tests
- Only tests that don't fail consistently are considered flaky
