### ISSUE TITLE
Improve efficiency of test resources cleanup tool

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1399]
Left over test resources such as test images are cleaned up with a [cleanup tool](https://github.com/knative/test-infra/tree/master/tools/cleanup) that runs weekly, which has been having trouble catching up cleaning up as we have expanded Boskos pool from 20 to 75 projects since the tool was implemented. 

The performance of the tool is not ideal as it's running cleaning up in sequential order, which means it `recursively` lists images and deletes them one by one. We should improve the tool to allow it doing these jobs in parallel so that it can do the job much faster

**Comment by adrcunha** [comment]
I'm running the cleanup script locally to get rid of the backlog quicker. After that, with 1523 merged, the cleanup job shouldn't timeout anymore (some fine tuning might be necessary though, but the logs will tell).

**Comment by adrcunha** [comment]
Fun fact: if you run the cleanup tool locally, it will reach the registry quota (500K HTTP requests/day) in a day or two (https://cloud.google.com/container-registry/quotas)

**Comment by chaodaiG** [comment]
Curious about Prow ip address, is it different per pod or there is a global
limit for Prow

**Comment by adrcunha** [comment]
Please note that this is about running the tool locally, i.e., on your own workstation.

**Comment by chaodaiG** [comment]
noted. The question was more a concern of whether the period cleanup job would also resulted in the quota limit problem. I have seen a really bad quota limit where it restart the timer even with a single query, and hopefully this one is not the case

**Comment by adrcunha** [comment]
Unfortunately the answer is "yes", because it's a single job (not sure about restarting the quarantine period). Proof at the end of the log: https://00e9e64bac8a874e2dfb250f02aceca14d0ba5502d236b32f1-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/logs%2Fci-knative-cleanup%2F1189602484583141376%2Fbuild-log.txt?qk=AD5uMEt_mOHltxV11m0413_M4be1tSCX7BL3yRsWR9QaoWN24eZG_xxiXezD-SSTt0PKFQiow1WpNyA6HR0AHVUdidElc7qOEQ4WHpu3DLT7qMmyxqjL0FVnp6kQn796WfYk8g95Sl7RVHDGv8yHYKVOXhgQ90LoCSOlF6-wyDx75kOYNaAve0hpGnPJJVXNdZkfXiX_18fNqfpHe_e9PxChEjdh6xCEmWj6vflyoHj75L7O881sRPBvHPAyyJxVrYjJ2HEuXBncjhSs8tsQ_-RbEmQt_witeBTYaWyuy3cSBE6NBueDj9A3SSYtudYq-ThglPf2vaU5hWtMhBbGdchCqDlSN8jgb635s90hrKm9zvqcIk8FKsO2zwtKHJZpYmbGQ3n47HRgTeQi3RrUAZqQndY2VVnPdXAGLrzGX4PP6g1ta8FxhYsFVPWD5AtEOJjVPBxDoLVYtfeKiaAzvAs6ykc383PXmlG0hfVIeFbw_toZpd9HBk5FYKYwrVo3rG1eVQSjPpVOAcQxuwvp4mZrZrV_v9w3SJJRNZkQwQoyfQOAqI_LXasapBbwaFN7y9M-9t_a1oKacMW6_OO1UGLZgwsY6_KxwT4CpypiVGMczzGf4PMk2OZpcaC1neddotcco6QmtL_XdGOmgztMiOmrgFg4wIgR1PE2r0bgZ6rCOrx0GrUzeeLag_QcTuSP-V5jbtblfZISFW7aZh2dit-1dfSatP9cUGBhKT-Az0XdYLVpRMwbvzH_Ui-_Yy17QTi7DU8QeF5nquzcyvRaTC3ZhpaU6140QZjKsu5s3ttNdL-RW37eJkjBydiDvs-HPbSHzJbRsSOGxUJBuS1JTk_vEL4sTGLN_6tBdB_MQCab8BtjEgxLjEE
