### ISSUE TITLE
Intermittently getting "boskos failed to acquire project" error

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1533]
For the integration tests Prow jobs, we intermittently got "boskos failed to acquire GKE project" error:
```
2019/11/07 02:47:45 failed acquiring GKE cluster: 'failed acquiring boskos project: 'boskos failed to acquire GKE project: status 500 Internal Server Error, status code 500'
```

Expanding boskos pool to 100 (https://github.com/knative/test-infra/pull/1529) does not seem to have solved this problem. 

Based on the discussion, @chaodaiG has a suspicion that it's because there is a race condition for compute resources between boskos pods and test pods since they are living in the same node pool of the Prow cluster, thus separating them into different node pools should help solve this problem. Before working on this solution, we need to collect relevant metrics to justify it.

**Comment by chaodaiG** [comment]
This is getting worse, it's happen pretty frequently now, see example: https://testgrid.knative.dev/serving#istio-1.4-no-mesh&width=20&exclude-non-failed-tests=50&sort-by-failures=

We should prioritize investigating and fixing this. 

/assign @yt3liu

**Comment by chizhg** [comment]
The boskos image update did not fix the issue.

After looking into boskos source code, I'm pretty sure it falls into  https://github.com/kubernetes/test-infra/blob/0c5566a3f019399377910bed349c2c280f5539e8/boskos/ranch/ranch.go#L155 when the error happens. One step further, it is https://github.com/kubernetes/test-infra/blob/0c5566a3f019399377910bed349c2c280f5539e8/boskos/crds/crd_storage.go#L52.

The keep error log is
```
{"error":"Operation cannot be fulfilled on resources.boskos.k8s.io \"knative-boskos-03\": the object has been modified; please apply your changes to the latest version and try again","level":"error","msg":"No available resource","time":"2019-12-11T06:24:20Z"}
```

Let's look it deeper tomorrow.

**Comment by chaodaiG** [comment]
I figured this out too, looking into more info

**Comment by chaodaiG** [comment]
When I check this morning, the Boskos container in Prow cluster was still using the old image. There are 2 observations:
- Boskos is configured as statefulset, which needs more manual step adopting new image. See config here: https://github.com/knative/test-infra/blob/master/ci/prow/deployments/boskos_statefulset.yaml
- Boskos in k8s/test-infra was switched to deployment instead of statefulset in this PR: https://github.com/kubernetes/test-infra/pull/13594

**Comment by yt3liu** [comment]
In the Stackdriver logs, the first error started to happen in November 11, 2019. 

First error in boskos container [[Stackdriver log]](https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=knative-tests&minLogLevel=0&expandAll=false&timestamp=2019-12-11T17:35:34.783000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-11-11T17:36:27.000000000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.namespace_id%3D%22test-pods%22%0Aresource.labels.project_id%3D%22knative-tests%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22boskos%22%0Aresource.labels.pod_id%3D%22boskos-0%22%0A%22Resource%20gke-project%20not%20exist%22%0A): 2019-11-11 09:36:24.000 PST
First error from test run [[Stackdriver log]](https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=knative-tests&minLogLevel=0&expandAll=false&timestamp=2019-12-11T17:22:15.814000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-11-12T20:20:10.629658500Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.namespace_id%3D%22test-pods%22%0Aresource.labels.project_id%3D%22knative-tests%22%0Aresource.labels.zone:%22us-central1-f%22%0A%22status%20500%20Internal%20Server%20Error,%20status%20code%20500%22%0A): 2019-11-11 11:00:17.228 PST

Around the time, the boskos pool was increased to 100 on November 6 [(Pull Request)](https://github.com/knative/test-infra/pull/1529). As boskos writes data to persistent volume before https://github.com/kubernetes/test-infra/pull/13594. The suspicion is the persistent volume may not be able to handle 100 projects. 

Next step is to switch boskos to deployment instead of statefulset mentioned earlier after confirming with k8s team.

**Comment by chaodaiG** [comment]
Updating Boskos to latest version fixed the problem

/close
