### ISSUE TITLE
Prow-tests image uses versioned tags instead of "stable"

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1556]
`prow-tests` image is used for most of Prow jobs for Knative repos, currently `stable` tag is used for locating image, such as: https://github.com/knative/test-infra/blob/fad831028edbe066665977ea7bf366c3d5c0a2d1/ci/prow/config.yaml#L226

This approach works pretty well initially as it allowed fast recovery when certain image doesn't work well, but due to increased complexity of Knative repos the only tag doesn't always fit all jobs, such as the introduction of `stable-go112` tag: https://github.com/knative/test-infra/blob/fad831028edbe066665977ea7bf366c3d5c0a2d1/ci/prow/config.yaml#L272

To be able to scale well, we should start exploring using versioned tag for each job instead of `stable`

**Comment by coryrc** [comment]
Why not separate image names instead of separate tags?

**Comment by coryrc** [comment]
I like :stable because it is trivial to rollback a broken change.

**Comment by coryrc** [comment]
We need to be able to update old versions of prow-tests, so this doesn't help anything. We should just close.

**Comment by chaodaiG** [comment]
> We need to be able to update old versions of prow-tests, so this doesn't help anything. We should just close.

What's your proposed solution for preventing issues like https://github.com/knative/serving/pull/7597#issuecomment-615010119

**Comment by coryrc** [comment]
My proposed solution is actually testing changes first before deploying or don't prevent them.

If indeed a separate image is needed for different releases, then there should be a separate image, like prow-tests-release-0.11 so it can be recreated.

Otherwise, if you need to do a security fix, you have no ability to just make one change without digging deep in the history and choosing an arbitrary point and have to effectively do the above without any help.

**Comment by chaodaiG** [comment]
Makes sense to me. IMO it also depends on which level of compatibility prow-tests image we want to provide. 

@chizhg has a proposal of pinning the versions of tools that are now part of prow-tests image in target repo, which should greatly help with the compatibility of prow-tests image
