### ISSUE TITLE
Question: any plan to add `start_knative_eventing` to test-infra?

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/test-infra#1566]
I would like to enable e2e test for eventing in Client project, refer to https://github.com/knative/client/issues/531. I want to know if there is any methods I can leverage in test-infra to start eventing infrastructure. If no, are there any plans to add it ?

**Comment by adrcunha** [comment]
No plans, feel free to add it. I imagine something along the lines of start_knative_serving, but @chizhg might be able to help/clarify.

**Comment by chizhg** [comment]
We don't have it in test-infra just because it is not reusable.
Now that we can reuse the function in both Knative client and eventing, there is a good reason to add.

Feel free to submit a PR for it, it should be just as simple as the one we now have for serving - https://github.com/knative/test-infra/blob/a130cd2df6c15aecdcb8be97f5579ed4532d19f9/scripts/library.sh#L410
