### ISSUE TITLE
Rewrite test script to Golang

### ISSUE THREAD

**Issue by cardil** [knative/test-infra#1587]
## Proposal

I would like to propose to rewrite existing test scripts to Golang.

## Problem

Writing scripts in Bash is troublesome and many developers and testers struggle to write them. Bash scripts are hard to write as the language has its quirks (see https://github.com/koalaman/shellcheck/blob/master/README.md#gallery-of-bad-code as an example). Additional linters are needed to assert quality of code.

Produced Bash code is hard to read and hard to extend as declaration is often linked execution.

Using scripts to set up environment forces to use command line to execute and develop tests. It's often hard or not possible to execute tests directly from IDE like Goland, VSCode.

By using scripts we are enforcing environment that can execute them. It will be nice to be cross platform. That's also is related to extra tools that are often needed to be installed.

Using scripts forces people to rely on vendoring of this lib and traversal of path to `vendor/` directory. It will be nice to enable users to utilize Golang modules in full force.

## Proposed solution

By creating Go library containing code that perform the same operations as current scripts do we should fix all of above points. Such a lib can mirror tools like http://arquillian.org both for managed and remote modes.

Also, it's easy to have Golang scripts that can be invoked with `go exec ..` if needed.

PoC "germ" of such library can be seen here: https://github.com/cardil/operator-e2e-harness and in this PR https://github.com/openshift-knative/knative-eventing-operator/pull/79

Below are example of how that might look like:

### Test main

```go
//+build e2e

package e2e

import (
	"os"
	"testing"

	"knative.dev/test-infra/pkg/test/catalogsource"
)

// TestMain is a main test runner
func TestMain(m *testing.M) {
	catalogsource.Deploy()
	code := m.Run()
	catalogsource.Undeploy()
	os.Exit(code)
}
```

### Example test

```go
//+build e2e

package e2e

import (
	"knative.dev/test-infra/pkg/test/config"
	"knative.dev/test-infra/pkg/test/context"
	"knative.dev/test-infra/pkg/test/olm"
	
	"testing"
)


func TestBasicLifecycle(t *testing.T) {
	ctx := context.NewContext(t)
	defer ctx.Cleanup() // will remove subscribtion and cr at test end
	ns := "operators"

	olm.InstallOperator(ctx, "example-operator", ns) // and waits for ready
	olm.AddCustomResource(ctx, "example-cr", ns)  // and waits for ready
}
```

**Comment by coryrc** [comment]
Several people are investigating solutions to this problem.

One big problem is e2e or conformance test CI run require a cluster created after a build succeeds, but they also need to run with an existing cluster in development. They also need to tear down the cluster after all tests are run (which run in multiple packages, so TestMain does not work) and process the output into JUnit. We use a number of CLI utilities to do the work, so a replacement Go code is just going to be calling a lot of shell code commands and ultimately not be much more maintainable for the amount of work.

I agree the bash scripts are way too complicated, and I think they can be simplified as there are a number of functions unused. We could simplify and put the important core functionality in one place. And instead of a number of flags, one script for each test target (build, unit, e2e, conformance)

**Comment by coryrc** [comment]
I think Chi's kntest proposal supercedes this nor is the approaches discussed here viable, so

/close
