### ISSUE TITLE
Refactor test-infra Scripts by Role

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1600]
## Problem

Our test-infra scripts are doing multiple jobs all mashed into one script:

1. Act as test runner
2. Setup and teardown for CI flows
3. Execute a particular test suite

Normally if a change is desired, someone only wishes to affect one of these three areas. Having these three intermixed makes every change more fragile and requires someone to understand all three components just to change one. It also makes self-service of repos impossible.

## Proposal

The goal of this PR is to split the scripts into three separate groups and not to rewrite them! The changes:

1. Test runner to be simplified and continue to mostly live in test-infra (this is presubmit-tests.sh). This part then becomes optional if someone uses a different job definition system.
2. Setup/teardown to be separate scripts living in (TBD: test-infra or each repo?), called by presubmit-tests.sh. As it's a separate script, it can easily be replaced for others who want to create clusters in other environments, upload results a different way, etc.
3. Each separate step (build tests, unit tests, e2e tests, coverage analysis) to be a separate script maintained in each repo. Each will need to have comments specifying the environment variables needed to run it and what its output is (where it place JUnit report, etc). At the conclusion of this PR, there should only be about one line of code in each file; for example, e2e tests would just have `go_test_e2e ./test/e2e || fail_test`.

All scripts should require one common library script still being hosted in test-infra.

## Enables Future Work

The completion of this PR enables any given section to be replaced with another tool or ported to another language where it makes sense. Replacing 1. is being investigated by @adrcunha and 2. has had work by @chaodaiG.

## Timeline
I, Cory, will do this work around the second half of January 2020. Feel free to do this before me if you wish.
/assign @coryrc 

## CC list
@adrcunha 
@cardil
@chaodaiG 
@nbarthwal 
@chizhg

**Comment by coryrc** [comment]
@pbuzek

**Comment by adrcunha** [comment]
I don't think this is the right approach. Simply splitting the scripts with the expectation that they can be replaced by another tool or script means that you're not changing the framework, but just being even more coupled with it.

1 is independent of the CI/CD system, and we're not going away from Prow in the foreseeable future.

2 had work done by Chao, yes, but only for the replacement of kubetest. This should be a new design, as briefly discussed in the last WG meeting.

3 is non trivial and is just a refactoring with the same constraints of the current framework.

I'm more in favor of coming up with a new design and work on that instead.

**Comment by chizhg** [comment]
I think the right direction will be designing and developing our own test driver in Go, e.g. `kntest` (of course we can give it a better name if people do not like it).

There are a couple of reasons for me to consider this approach:
1. As @coryrc pointed out in https://github.com/knative/test-infra/issues/1587, we cannot use a single `TestMain` to do the setup and teardown, since `TestMain` is tied to a package, but sometimes we want to run tests from multiple packages, like in serving - https://github.com/knative/serving/blob/bcf14aac12a0a8e8baa6294bd7df1deaeeaca55b/test/e2e-tests.sh#L51, and we don't want to create clusters and/or install serving for running tests in each package.

2. We do want to use Go since the whole Knative project is written in Go.

3. We should not reintroduce `kubetest` since it involves a lot of logics that we do not care, and it's hard to chime in our own logics.

4. Kubernetes community is now actively developing [kubetest2](https://github.com/kubernetes/test-infra/tree/master/kubetest2). It already has some common libraries that we can potentially use, and we may also be able to explore more opportunities to collaborate.

**Comment by coryrc** [comment]
Chi is solving 2 with `kntest`.

1 was always a small task, as the file is mostly standalone.

1 & 3 will be supplanted by Tekton Pipelines, work which has already begun.

These other issues are tracked separately, so this issue isn't needed anymore.
