### ISSUE TITLE
Document default resource requests for Prow jobs

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1734]
It seems we have default resource requests of 8.6GiB memory and 4 vCPU, but I can't find where this is configured. We should document this.

**Comment by chaodaiG** [comment]
They are configured here:
https://github.com/knative/test-infra/blob/master/config/prow/cluster/200-cpu-limitrange.yaml
https://github.com/knative/test-infra/blob/master/config/prow/cluster/200-memory-limitrange.yaml

The reason for 8.6 GiB instead of 8GiB I believe was because of each sidecar takes 200M

**Comment by coryrc** [comment]
Ah, thanks. I will find an appropriate place to document.
/assign

**Comment by coryrc** [comment]
oops, wrong number
still open

**Comment by coryrc** [comment]
/open
?

**Comment by coryrc** [comment]
we have deleted default resource... but we should document what the config generator does somewhere
