### ISSUE TITLE
Investigate octobox.io for knative notifications

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#174]
This came up from slack discussions.
Both @bbrowning  and markus.thoemmes are recommending [octobox.io](https://octobox.io/) as a great tool for catching git notifications.  and it also supports "Run your own Octobox"

**Comment by bbrowning** [comment]
Funnily enough, I got notified of this issue via my Octobox tab!

Prior to Octobox, I managed GitHub notifications via Gmail labels and filters. That worked, to an extent, but all too often I found myself avoiding anything to do with email because of all the other distracting and tempting unread things that lurk there.

Now I have a pinned tab in my browser for Octobox and I can go there to see any GH issues that need my attention or that I subscribed to and have had recent activity. It's similar in spirit to the Gubernator PR dashboard, which I also keep in a pinned tab.

**Comment by jessiezcc** [comment]
cc @markusthoemmes 
It'd be beneficial to evangelize some of these notification mgmt tooling across the community as part of productivity wg initiatives.

**Comment by markusthoemmes** [comment]
Definitely, it's a great tool for anybody who's trying to stay on top of things, especially because you see for every notification why you got it in the first place (be it a mention, an assignment or just because you subscribed). I'll spread the word!

**Comment by jessiezcc** [comment]
We had discussion, no engineering work to be done here.
