### ISSUE TITLE
Drop the support for installing Istio addon on GKE cluster

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1787]
Currently in scripts/e2e-tests.sh, we support passing a flag called `--skip-istio-addon`. If it's passed, the GKE cluster created for the E2E tests will not have Istio addon enabled, otherwise the Istio addon will be enabled.

Istio addon is a GKE feature, we should drop it when we want to support running E2E tests for other Kubernetes providers. 

Note:
We cannot drop it now as a few projects, e.g. [knative-gcp](https://github.com/google/knative-gcp) depend on serving, and they are installing Istio addon as the default ingress. This issue can be solved by  following https://knative.dev/development/install/installing-istio/ to install Istio.

**Comment by daisy-ycguo** [comment]
I support to replace Istio add-on with standard Istio because I don't think Istio add-on could support our test cases very well. I have written down the [issue](https://github.com/knative/client/pull/719#issuecomment-597015940) I met with in a client e2e test case. And I see a gentleman had the same issue which was reported to [eventing issue](https://github.com/knative/eventing/issues/2266).
