### ISSUE TITLE
Dump controller/apiserver metrics in test run logs

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1837]
As asked by @grantr  on [Slack](https://knative.slack.com/archives/CCSNR4FCH/p1584644208171900), it would be helpful for debugging test errors if test-infra can support dumping the prometheus output from controllers .

/kind feature-request

**Comment by vaikas** [comment]
And just to be clear, what the end goal here (at least one) should be is to provide visibility on the load that we put on the API server. There's some tests that are being flaky and one hypothesis is that it's because API server is becoming overloaded. So, having some visibility in the number of operations that is being put on the API server seems useful. Ideally this would be broken down by each test.
