### ISSUE TITLE
Auto config updater fails silently

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1935]
Auto config updater is doing pretty well most of the times, but when it failed it did it in a silent way, it's pretty hard to figure out unless the PR author kept on poking PR status page for the bot comment. 

An example failure:
https://prow.knative.dev/view/gcs/knative-prow/logs/post-knative-prow-config-updater/1252724334305218561

**Comment by chizhg** [comment]
The reason is because we are using the commit ID to get the PR number for postsubmit jobs, as we are always configuring Tide to use squash to merge PRs. It seems there is some delay when Github correlates the commit ID with the pull request thus the error.
The fix would be adding PR number as an env var in postsubmit jobs for Prow, then we won't need this hack anymore.

**Comment by chaodaiG** [comment]
Not relevant any more
/close
