### ISSUE TITLE
Unified story of using k8s/test-infra tools with bazel

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1970]
There are currently a few places where bazel are used in this repo, based on the usage this can be divided into these categories:
- Used only by test-infra:
  - [Update testgrid config](https://github.com/knative/test-infra/blob/f645de8d9a500a3fd00149f1b4e693029d678132/config/prow_common.mk#L120)
  - [run_job.sh](/config/prow/run_job.sh)
- Used by other repos 
  - Installed in [Prow test image](https://github.com/knative/test-infra/blob/f645de8d9a500a3fd00149f1b4e693029d678132/images/prow-tests/Dockerfile#L53)

For the usage only by test-infra, the bazel runtime is declared by an out-dated [WORKSPACE](/WORKSPACE) file, which has been so old that it's almost not possible to keep it up-to-date. We need a better story with using bazel

/cc @chizhg

**Comment by chizhg** [comment]
@cjwagner Do you have a suggestion on how to solve this issue? How are other repos running commands from k8s/test-infra repo such as `mkpj`? Thanks!

**Comment by cjwagner** [comment]
All Prow binaries are published as container images and all images are published together whenever one changes so that a consistent image version tag can be used across Prow components. Using components with different versions together or building with bazel from an arbitrary commit can cause in problems due to version skew between components. e.g. using a newer version of `mkpj` than `plank` could create PJs that use fields that are not yet considered valid by plank.
All the available images can be found under [gcr.io/k8s-prow/](https://gcr.io/k8s-prow/)
Here is an example use of the `mkpj` and `mkpod` containers: https://github.com/kubernetes/test-infra/blob/c5d8bee32b32fba5d2fa278acc0950ab88715d7f/prow/pj-on-kind.sh#L29-L30

**Comment by coryrc** [comment]
So we'd `docker run` them somehow?

**Comment by cjwagner** [comment]
> So we'd `docker run` them somehow?

Yes, see my link above for some example `docker run` commands for `mkpj` and `mkpod`.

**Comment by chizhg** [comment]
> > So we'd `docker run` them somehow?
> 
> Yes, see my link above for some example `docker run` commands for `mkpj` and `mkpod`.

Thanks Cole!!

It seems `//testgrid/cmd/configurator` is not built as an image, or maybe it was in a different registry? If indeed not, can we built it as an image as well?

**Comment by cjwagner** [comment]
> It seems `//testgrid/cmd/configurator` is not built as an image, or maybe it was in a different registry? If indeed not, can we built it as an image as well?

@chases2 Is there a configurator container image already?

**Comment by chases2** [comment]
There is an image of configurator at `gcr.io/k8s-testgrid/configurator`, though that location may change in the near future. It should be part of the Prow registry with other tools.

**Comment by chaodaiG** [comment]
Fixed
/close
