### ISSUE TITLE
Automate new repo onboarding

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#207]
is it possible to have a single click experience to onboard a new repo? Today, we have to make separate code changes to enable prow, code coverage, testgrid and etc. Since it has been repeated for a few repoes now, wonder whether we can further automate it to be a single step.

**Comment by adrcunha** [comment]
https://github.com/knative/test-infra/pull/204 should clarify the process even more. A "single click" experience isn't possible because onboarding a new repo also requires updating Prow (thus outside of GitHub realm). We could have a script to do that, but it won't solve the manual step of merging at least one PR. Having a few scripts to make the task easier could help (for example, as I already mentioned, a Prow config generator based on a more simple repo definition yaml). But since we don't create new repos very often I believe this is too much effort for a low priority need.

**Comment by jessiezcc** [comment]
Not a priority.
