### ISSUE TITLE
Go version should be defined in-repo

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2118]
Each repo should be able define what GO_VERSION becomes when running jobs. The configuration generator can provide a default value, but each repo should have a way to define what version of Go it desires.

Advantages:
1. Each repo can decide when to switch Go versions w/o waiting on test-infra to update jobs
2. Running tests in docker allows the GO_VERSION to be determined accurately without having to keep scripts updated or intertwined with the config generator.
3. Simplifies the config generator
4. Historical versions will stay accurate

I recommend this be done an extensible way by having [runner.sh](https://github.com/knative/test-infra/blob/master/images/prow-tests/runner.sh) source a shell script in each repo root (or some other location?), if it exists.

/cc @peterfeifanchen @chizhg

**Comment by chizhg** [comment]
FYI the go version is already specified in `go.mod` file, see https://github.com/knative/test-infra/blob/master/go.mod#L3, so there is no need to add any extra logic in each repo.

The go version selection logic should be in the test driver scripts, e.g. `presubmit-tests.sh`, since we need the repo's source code to be in place first.

**Comment by chizhg** [comment]
Actually I was wrong about this. `runner.sh` is the initial test driver, so we can put the go version selection logic there.
