### ISSUE TITLE
Assess rewriting bash scripts to go

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2398]
Background: knative/test-infra repo contains a bunch of bash scripts under https://github.com/knative/test-infra/tree/master/scripts, which are vendored and imported by other repos. As proposed by @cardil  and discussed on [productivity WG meeting](https://github.com/knative/test-infra/tree/master/scripts) that it's possible to transform these bash scripts to Go equivalent, serving same role, while has the advantage of proper testing in place

/cc @cardil @chizhg @albertomilan

**Comment by n3wscott** [comment]
We have been asking for this for over a year. The main issues with all this bash is there are no tests and it is too complex.

**Comment by chizhg** [comment]
I have some updates and more thoughts on this in my recent work:

Since knative test-infra is already using [`kubetest2`](https://docs.google.com/document/d/10Zfu0KiJVMxHL-rNMW9pOESdFcdCuw2ABrDFKVQqooM/edit#) which introduced a nice concept of decoupling `tester` from the `deployer` lifecycle, and it has been well accepted by the Kubernetes community, I think we should borrow the idea as much as possible for Knative integration testing.

In https://github.com/knative/test-infra/pull/2412 I built a `kntest` wrapper command for `kubetest2`, which incorporated some defaulting and retrying logic that are specific to Knative integration testing. After it's merged, running integration testing in CI could be as simple as `kntest kubetest2 gke [kubetest2-flags] --test=exec -- [test-command]`.

Eventing team is looking into implementing new testers for e2e and conformance tests, potentially with `Go`. After it's implemented, we could replace the `./test/e2e-tests.sh` in Prow job with the above `kntest` command (the [test-command] could be like `go run e2e-tester.go` or even further, we can extend the `tester` type, so the arg will be `--test=e2e-tester`.)

If this approach works well for Eventing, we can fanout it to other Knative repos and deprecate all the bash scripts in `test-infra/scripts` in the end.

**Comment by chizhg** [comment]
cc @devguyio @lionelvillard @n3wscott @slinkydeveloper

**Comment by cardil** [comment]
@grantr could you move this issue to knative/hack repo?

**Comment by cardil** [comment]
/remove-lifecycle stale

I'm still targeting this. Hopefully soon, now... :crossed_fingers:

**Comment by cardil** [comment]
I think this is doable by splitting this into smaller tasks:

- Installation of knative components (latest, specific release, head) - task for specialized lib+tool that might be reused in other production codebases (operator, cli plugins)
- updating deps, generating code - specialized lib+tool that can be embedded within build tools
- launching test clusters - there are tools for this already, but we could move leftover code to either existing tools or write new libs that will orchestrate the process.
- test running and reporting - again a lib+tool which will handle this

@chizhg please take a look at above. Did I missed something? If no, I'll close this issue and open other ones more targeted at above tasks.
