### ISSUE TITLE
prow: Tide can't set status due to hitting status limit

### ISSUE THREAD

**Issue by chases2** [knative/test-infra#2847]
```
insertId: "ggznmr8r91pnor0y"
jsonPayload: {
base-sha: "bb2946c67454d352f730c67a06ff23d050727a13"
branch: "main"
component: "tide"
controller: "sync"
error: "status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}"
file: "prow/tide/tide.go:1214"
func: "k8s.io/test-infra/prow/tide.(*Controller).mergePRs"
level: "error"
merge-targets: [1]
msg: "Unable to set tide context to SUCCESS."
org: "knative-sandbox"
pr: 87
repo: "async-component"
sha: "952459cb0ed4ba9408a428edddd76e87c8ef4aa4"
}
labels: {
compute.googleapis.com/resource_name: "gke-prow-prow-prod-pool-64be9565-iq2s"
k8s-pod/app: "tide"
k8s-pod/pod-template-hash: "5c88695f46"
}
```

Tide seems to be repeatedly retrying to set this status; this error (or similar) is occurring pretty regularly

**Comment by shinigambit** [comment]
According to the logs the PR causing the issue is this one knative-sandbox/async-component/pull/87 but nothing out of the ordinary seems to have happened on it that would trigger that many status updates. It should do more that 1000 updates to trigger this error according to the documentation https://docs.github.com/rest/reference/repos#create-a-commit-status 

Is there any retry logic around this call in Tide that could be responsible of attempting that many updates?
