### ISSUE TITLE
Reduce the infra cost for Knative

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#3104]
Currently the infra cost for running Prow, E2E tests, release pipelines is around $50K per month. There have already been some efforts to reduce the cost. As part of the effort for CNCF infra migration, we want to further reduce the cost as much as possible before fully handing off the infra to the Knative community.

The current infra cost breakdown can be checked from https://github.com/knative/test-infra/issues/3003

Below are some tracking issues that could help:
- [x] https://github.com/knative/hack/pull/138
- [x] https://github.com/knative/test-infra/issues/3096
- [ ] https://github.com/knative/hack/issues/153
- [ ] https://github.com/knative/test-infra/issues/2985
- [x] https://github.com/knative/test-infra/issues/3117
- [x] https://github.com/knative/test-infra/pull/3214
- [x] https://github.com/knative/test-infra/issues/3120
- [x] https://github.com/knative/test-infra/issues/3121
- [x] https://github.com/knative/test-infra/issues/3127
- [x] https://github.com/knative/test-infra/issues/3128
- [x] https://github.com/knative/test-infra/pull/3129
- [x] https://github.com/knative/test-infra/issues/3130
- [ ] https://github.com/knative/test-infra/issues/2466
- [x] https://github.com/knative/test-infra/issues/3163

/kind cncf-infra

**Comment by mattmoor** [comment]
From the meeting: we should be very very very careful about any sort of image cleanup.

There was cleanup logic added to Knative very early on which ended up doing an `rm -rf` on our public release public and burned a day or so of my and others time getting the GCR/GCS teams to restore it from backups.

If release images aren't a significant cost, then please just don't touch them.

If they are, the cost is almost certainly egress, and whatever solution we implement should shadow what Kubernetes is doing to solve this (still WIP), which does NOT involve deleting things, but mirroring them to avoid egress charges.

---

On GCS object lifecycle management, I said "don't turn it on", but this was really aimed at using it to GC old blobs.

The more nuanced answer is: OLM should absolutely be turned on, but the feature around retaining older generations of objects so that we don't have to page the GCS oncall to restore things from backup.  The features that allow object TTLs should absolutely never be used on a GCR bucket.

Turning on OLM to avoid paging GCS was one of the requests from the GCS team when we had to restore things from backup (above).

**Comment by chizhg** [comment]
/cc @upodroid @kvmware 

This issue is tracking all the work we are doing / planning to do to reduce the infra cost. If you have other ideas, please create a new issue and link it here. If you have concerns on the existing issues, please leave comments under the corresponding issue. Thanks!

**Comment by chizhg** [comment]
As of now, we have met our goal to reduce the infra cost to below $250k/year (the cost for 2022/04 was ~13k so the year round will be ~$156k). The remaining tasks initially added to this issue are good-to-have and are already tracked in separate issues. Closing this issue to mark it as resolved.
