### ISSUE TITLE
Serving performance grid seems to be messed up

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#335]
![image](https://user-images.githubusercontent.com/35786489/50181048-2a68d300-02c0-11e9-9a80-30aa8d424644.png)

**Comment by srinivashegde86** [comment]
the observed concurrency test was refactored and hence the new cells. I have fixed the tests and added the latency runs and should start to be visible once the perf run passes.

The latest perf run failed due to insufficient resources - https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-performance/1075194178993917953/?log#log

Will wait on the next run to confirm

**Comment by markusthoemmes** [comment]
Test results are not properly parsed now at all

See: https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-performance/1075556566633025537/

I think prow can only handle a single `<testsuite>` element per XML file and we're creating multiple with our tests.

**Comment by srinivashegde86** [comment]
That seems to be the issue.

Seeing 
```
Gubernator Internal Fatal XML Parse Error 0.00s
junk after document element: line 18, column 0 from junit_knative.xml
```

Logs:
https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-performance/1075556566633025537/#gubernator-internal-fatal-xml-parse-error

Based on testgrid code, it can handle multiple testsuites, but gubernator is throwing a ParseError.

**Comment by srinivashegde86** [comment]
Multiple testsuites seem to be fine, but they need a parent element, which is missing

```
<testsuites>
<testsuite>......</testsuite>
<testsuite>......</testsuite>
</testsuites>
```

**Comment by srinivashegde86** [comment]
Fixed by https://github.com/knative/serving/pull/2770
