### ISSUE TITLE
Remove redundant markdown lint from presubmit-test.sh 

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#3383]
https://github.com/knative/test-infra/blob/d41432f3e415994399b2ea328675e2284451b83b/scripts/presubmit-tests.sh#L138 this is handled by github actions.

**Comment by kellyaa** [comment]
I noticed the link to `presubmit-tests.sh` is in the now non-existent `test-infra/scripts` folder -- It's been relocated to the hack repo. I also noticed that the [same file in the hack repo](https://github.com/knative/test-infra/blob/main/vendor/knative.dev/hack/presubmit-tests.sh) no longer has those lines for running linting. Although its references are still in the [README.md](https://github.com/knative/test-infra/blob/main/vendor/knative.dev/hack/README.md).

Does this mean that this issue is no longer valid (except for maybe readme updates)? Or am I missing something?
