### ISSUE TITLE
A centralized place defining release yaml naming conventions

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#472]
Each repo defines the release yaml names under `hacks/release.sh`, the names are mirrored in test-infra repo under `scripts/library.sh`, this could cause error if any updates not happening on both sides at the same time.

**Comment by adrcunha** [comment]
Note that these are different things: `release.sh` generate the manifest files, but the location is predetermined. `library.sh` has convenience URLs pointing to the most used manifests. When Knative was released as a single bundle, it made sense having differente names (build.yaml, serving.yaml, etc). But with the (recent, still ongoing) decoupling, the tendency seems to be using release.yaml for each module (except for some other special yamls, like Istio). This issue might become unimportant once all Knative modules use "release.yaml" as the name of the main manifest.

**Comment by jessiezcc** [comment]
let's solve it when we rewrite shellscript later.

**Comment by adrcunha** [comment]
I'm closing this as the yaml names (at least those used by library.sh) are now pretty stable due to the convention used across Knative modules. I don't think it's worth creating an inter-dependency between each module and test-infra just because of yaml names. And since this might change based on whatever new comes from [issues tagged with test-infra-next], this issue is likely to be either obsolete or addressed by then.
