### ISSUE TITLE
Cleanup job should also delete leaked networks

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#629]
Complementing #390, leaked networks should be cleaned up as well (deleting a cluster doesn't guarantee that). The cleanup code can be "borrowed" from `scripts/e2e-tests.sh`.

/assign @chaodaiG 
(not urgent though)

**Comment by chaodaiG** [comment]
Scanned PRs in serving since PR#3000 (Jan. 25th 2019), both in `pull-knative-serving-integration-tests` and `pull-knative-serving-upgrade-tests`, the code path `Found leaked` at line [L137](https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L137) and [#L142](https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L142) were not hit at all.

Running serving e2e tests locally 10 times while commenting out `delete_leaked_network_resources`, and didn't get any leaked networks.

So this work might not be needed anymore, we can even consider removing `delete_leaked_network_resources` so that the [`TODO`](https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L125) can be resolved

**Comment by adrcunha** [comment]
This is indeed a good signal. As synced offline, let's keep the cleanup job running for a while, then check its logs. If no leaks are found anymore, let's remove the cleanup function.

**Comment by adrcunha** [comment]
@chaodaiG it's been almost 2 months, if there are no network resources leaked anymore, should we remove the function and close this?

**Comment by chaodaiG** [comment]
@adrcunha , scanned again, there has been no network resources leaked anymore. Removed in PR #921

**Comment by chaodaiG** [comment]
/close
since it's obsolete now
