### ISSUE TITLE
remove post-knative-serving-go-coverage as defaultPostSubmitJobName

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#645]
We are running code coverage on multiple repos and we are running it not only in pre-submit.
Periodical jobs and post-submit jobs do not need the flag and it is distracting to set the defaultPostSubmitJobName, as it would be printed in logs.

example from https://prow.knative.dev/log?job=ci-knative-client-go-coverage&id=1111070508478107650
postSubmitJobName=post-knative-serving-go-coverage;

**Comment by adrcunha** [comment]
Link to the log above from GCS:

https://storage.googleapis.com/knative-prow/logs/ci-knative-client-go-coverage/1111432895316103172/build-log.txt

I'm not sure what this issue is trying to solve. If it's an internal thing in the code coverage job, not a high priority. I would prefer such effort spent on a cleanup of the flags used in the jobs in the Prow config.
