### ISSUE TITLE
Integration tests are failing with the istio dependency

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#718]
Our e2e tests verify the installation steps in knative serving. But, serving recently stopped publishing istio yamls once https://github.com/knative/serving/pull/3918 got merged. But, we are still trying to install it and failing.

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/712/pull-knative-test-infra-integration-tests/1122583223629516802/

**Comment by adrcunha** [comment]
This is another variant of the decoupling mentioned in #675. This is a simple fix in library.sh.

**Comment by adrcunha** [comment]
I took a quick look, and unfortunately the fix is not trivial as I thought. https://github.com/knative/serving/pull/3918 removed the istio YAMLs from the releases (and the first nightly release succeeded yesterday, starting the general breakage), but the same Istio is still being installed for serving tests (and is the recommended way in the documentation).

As a stop-gap solution would be adding the Istio YAMLs to our GCS and updating library.sh accordingly so the repos are unblocked. Next step is to coordinate with Nghia and/or Matt about the right way of installing Istio (the one in serving's 3rd-party dir contains some modifications, so it's not just installing an official Istio distribution) for the tests.

**Comment by adrcunha** [comment]
Assigning to test-infra oncall.

/assign @nbarthwal

**Comment by adrcunha** [comment]
Scott might have an even neater solution for this (needs to be vetted by serving folks though):

```
 gcloud beta container clusters update ${E2E_CLUSTER_NAME} --region=${E2E_CLUSTER_REGION} --update-addons=Istio=ENABLED --istio-config=auth=MTLS_PERMISSIVE
```

See https://github.com/knative/eventing/pull/1117

**Comment by adrcunha** [comment]
Problem 1: the gcloud approach doesn't allow non-GKE k8s clusters to be used (e.g., eventing)
Problem 2: looks like updating the cluster with gcloud take waaaay too long... :(
```
I0429 18:12:54.491] Updating keventing-e2e-cls1122925479381176321...
I0429 18:30:24.871] .......done.
```

**Comment by adrcunha** [comment]
Looks like I CCed @mattmoor in the wrong issue, doing it here now.

**Comment by mattmoor** [comment]
> and is the recommended way in the documentation

Not anymore: https://github.com/knative/docs/pull/1243 :)

**Comment by mattmoor** [comment]
Can we create the cluster with Istio to start?

**Comment by adrcunha** [comment]
We surlly can, but better protecting that with a flag for now (defaulting to true). Our instructions should be updated to reflect the new behavior.

**Comment by dushyanthsc** [comment]
Work for this is complete, Chao will close this issue shortly.

**Comment by chaodaiG** [comment]
/close
since PR #734 is replicated in all repos
