### ISSUE TITLE
Flake test reporter should also report consistent failures

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#821]
We could use the flake test report to raise awareness of consistently failing tests.

@chaodaiG WDYT? A failing test could be considered flaky if there are passing and failing invocations in the period analyzed. I remember you had a special case for consistently failing tests, but I don't remember. If this case isn't handled by the reporter, would it be hard to do it?

**Comment by chaodaiG** [comment]
This case isn't handled by the reporter currently, and the logic doesn't distinguish this case from any other non-flaky case.

It would be just 1 line change if we want to treat it same as flaky tests. Otherwise depends on how we want to separate the logic it might take fair amount of work. Here are the questions in my mind:

1. Do we want to report in Slack like this(This isn't much work I believe):
```
Tests are flaky:
- Test_A
- Test_B
Tests consistently failing:
- Test_X
- Test_Y
``` 
2. Do we want github issue created for consistently failing tests? If the answer is yes, then the Github issue deduplication logic probably will need to handle flaky tests associated issue and consistently failing tests associated issues separately. The cleaner way I can think of doing this is introducing another label other than `auto:flaky`, such as `auto:failed-test`, and this might take a nontrivial amount of work, as the original design was pretty tight coupled with single label

**Comment by adrcunha** [comment]
I agree with both suggestions above. This is not high priority, feel free to assign it or work on it when it's convenient.

/assign @chaodaiG
