### ISSUE TITLE
Add zipkin tracing support for Knative tests

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#89]
as title suggests

**Comment by dushyanthsc** [comment]
[Commit](https://github.com/knative/pkg/commit/083969f9a02994963485eb8c9200c293ebf804a2) adds Zipkin tracing support to test infrastructure. However, fundamental requirement of this feature is the availability of Monitoring components installed on the KNative cluster. Currently, monitoring is not enabled by default for e2e tests due to [this](https://github.com/knative/serving/blob/master/test/cluster.sh#L68) which is blocked on Issue:[#647] (https://github.com/knative/serving/issues/647)

Till #647 is addressed, developers can enable Zipkin tracing for clusters setup with Monitoring using following instructions:

1. Setup KNative cluster with [Logging and Monitoring](https://github.com/knative/serving/blob/master/DEVELOPMENT.md#install-logging-and-monitoring-backends) enabled.
2. In the test-setup call Zipkin initializer.
3. As recommended for e2e tests, use SpoofingClient to communicate with your KNative cluster.
4. For the HTTP request that you would like to inspect Zipkin trace, call LogZipkinTrace()
5. In the test-cleanup call Zipkin cleanup

As an example a sample commit enabling zipkin tracing is available in this [repository](https://github.com/dushyanthsc/serving/commit/4f90405d225861f8ea53a15bd14f04b41d530cb9).

**Comment by jessiezcc** [comment]
@dushyanthsc, can this issue be closed now?

**Comment by dushyanthsc** [comment]
After talking to Adriano, we have decided to enable atleast Zipkin for E2E tests. I will work on this to enable Zipkin tracing. ETA at the moment is 02/22/2019

**Comment by adrcunha** [comment]
@dushyanthsc isn't this one done already?

**Comment by dushyanthsc** [comment]
I think this was picked up by @yt3liu

**Comment by yt3liu** [comment]
The previous change only enabled zipkin for performance test. Related issue: https://github.com/knative/test-infra/issues/539

That's done in this PR https://github.com/knative/serving/pull/3594/. Similar change can be done for all tests to enable zipkin.

**Comment by adrcunha** [comment]
Thanks, closing.
