### ISSUE TITLE
Prow job for keeping updated pkg in all repos

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#932]
As requested by @mattmoor , it would be nice if there is a prow job updating pkg in all repos. This job running periodically, creating PRs updating pkg, and should inform if there is a bad merge (i.e. still create a PR stating that there was a bad merge)

**Comment by mattmoor** [comment]
shut up and take my money :)

**Comment by srinivashegde86** [comment]
can we also have one for test-infra :D

**Comment by mattmoor** [comment]
I am experimenting with this for knative/pkg via the morning knobots job now.  I can play with test-infra if I can get that working.

**Comment by mattmoor** [comment]
So the way we futz with things in `./hack/update-deps.sh` means that this cannot simply be `dep ensure -update foo`, but I also can't simply run `./hack/update-deps.sh` in my template the way we do things today because the way we setup the `REPO_ROOT_DIR` undoes the symlink magic I use to present `dep` with the illusion of being on GOPATH.  🙄

**Comment by mattmoor** [comment]
If someone could take a peak at: https://github.com/knative/sample-controller/pull/10 I'll see if it unblocks this for `sample-controller` and if it does mirror the change elsewhere.

**Comment by mattmoor** [comment]
Alright, the `knative/pkg` case is a nop at the moment, but here's `knative/test-infra`: https://github.com/knative/sample-controller/pull/11 :)

**Comment by mattmoor** [comment]
Well, in the main repos we blow up updating licenses because of this line: https://github.com/knative/test-infra/blob/62c33c1b815e365539469b51682e20e6a3f40048/scripts/library.sh#L372

So my prior changes to `hack/update-deps.sh` were in vain because `REPO_ROOT_DIR` is my resolved symlink instead of the symlink on GOPATH :(

```
2019/06/15 19:56:15 Error collecting transitive dependencies: working directory must be on ${GOPATH}/src = /tmp/go/src
```

You can see what I'm doing [here](https://github.com/mattmoor/knobots/blob/3108ba473048e9f93e104f573d753568a90a61ea/config/dep-update-template.yaml#L27)

**Comment by mattmoor** [comment]
@adrcunha WDYT?  Could we support BYO `REPO_ROOT_DIR` or make `update_licenses` assume it's already there?

**Comment by adrcunha** [comment]
Let's support BYO `REPO_ROOT_DIR`, so we'll have flexibility built into all the scripts.

**Comment by mattmoor** [comment]
If that lands in test-infra, I can set it in my build template and it should just be picked up in the next update to each of the repos :)

**Comment by adrcunha** [comment]
Sure. You can simply LGTM 947 and wait. :)

**Comment by mattmoor** [comment]
I've update the template to set this, and I'll try this for serving now.

**Comment by mattmoor** [comment]
It seems to have worked in Eventing, but Serving is blocked on pulling in @srinivashegde86 change.

This is going to fail and require manual work anytime breaking changes are made to `test-infra`, so we should be more careful about making them.

**Comment by adrcunha** [comment]
@srinivashegde86 is the comment above still valid?

**Comment by adrcunha** [comment]
Not anymore, serving is done.

/close
